services:
  postgres:
    container_name: to-do-list
    image: postgres:17
    ports:
      - "5430:5430"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=todo_list_db